# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 450b40ed078eadf3b055968e0e40c0ef3b691df7862b21d4c3e86acc5f1f261d62c264f207b30c8856053e2716f0db1698500ff679d36b3c9122833c9ad69d23

test:
  secret_key_base: 7a5439e46ab7ebb6108f6c80762cbe315d5c1b20b8d052da584bcf06651adec07f75a6861c45ffe3a2b2096e0cce5488b4472ac174381eea6e0d4c1d6f5ca969

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
